name: create_release when tagged

on:
  push:
    tags:
      - 'v*'

jobs:
    tag:
        runs-on: small
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              with:
                tag_name: ${{ github.ref_name }}
                release_name: deploy-${{ github.ref }}
                draft: false
                prerelease: false