name: create_release_when_tagged

on:
  workflow_dispatch:
  # During test, to delete
  pull_request:

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Execute shell script
              run: |
                chmod +x ./build-deploy.sh
                ./build-deploy.sh
                ls -al
            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              with:
                body_path: ${{ github.workspace }}-CHANGELOG.txt
                repository: leboncoin/zoekt
                tag_name: deploy-2022-05-12T1308-d515d7a
                release_name: deploy-2022-05-12T1308-d515d7a
                draft: false
                prerelease: false
