name: release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Execute shell script
        id: build_deploy
        run: |
          chmod +x ./build-deploy.sh
          ./build-deploy.sh
          release_name=$(find . -name "zoekt-*.gz" | xargs -I'{}' basename "{}" | sed 's/zoekt-//' | cut -d. -f1)
          echo "release_name=$release_name" >> "$GITHUB_OUTPUT"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          repository: leboncoin/zoekt
          tag_name: ${{ steps.build_deploy.outputs.release_name }}
          files: zoekt-${{ steps.build_deploy.outputs.release_name }}.tar.gz
          draft: false
          prerelease: false
